Updating react-table to v7
OpenLiberty/draft-guide-rest-client-reactjs pull request #122
Opened 2023-01-19 10:46 UTC by jakub-pomykala

- Updating the react-table from v6 to v7
- Updating LMP to 3.7.1

2023-01-23 09:57 UTC, jakub-pomykala commented
For the super-linter check the env option to `VALIDATE_CSS` is set to `false` but it was still running checks on the CSS with `jscpd`. I managed to remove the failure by setting CSS styling that was flagged as clone to multiple elements at the same time.

2023-01-25 21:44 UTC, gkwan-ibm requested changes

2023-01-25 21:44 UTC, gkwan-ibm commented on README.adoc
> +The [hotspot=react-library file=1]`React` library imports the `react` package for you to create the [hotspot=ArtistTable file=1]`ArtistTable` function needs to have the `export` declaration as it is
The `Posts`  object...
->
The `posts`  object...

2023-01-25 21:44 UTC, gkwan-ibm commented on README.adoc
> +The [hotspot=useTable file=1]`useTable` hook is used to create a paginated table. The `useTable` hook takes in the [hotspot=table-info file=1]`columns` and [hotspot=Posts file=1]`Posts` objects as pa
... `Posts` objects ...
->
... `posts` and `setPosts` objects ...

2023-01-25 21:54 UTC, gkwan-ibm commented
Also, there are two `// tag::table[]` showing in the table and better update the table screenshot in the "Try what you’ll build"  section because the table bottom looks differently.

![Screen Shot 2023-01-25 at 4 50 11 PM](https://user-images.githubusercontent.com/29576299/214699603-a178b0da-b3c1-4de5-beda-2b5325748875.png)

2023-01-25 22:07 UTC, gkwan-ibm commented
at "Importing the HTTP client" subsection, should remove the following statement?

...Next, add the `componentDidMount()` method to your component.

2023-01-25 22:22 UTC, gkwan-ibm commented
Failed to run `mvn process-resources` in the "Building and packaging the front end" section

```
[INFO] Creating an optimized production build...
[INFO] Failed to compile.
[INFO] 
[INFO] Attempted import error: './Components/App' does not contain a default export (imported as 'App').
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 min
[INFO] Finished at: 2023-01-25T17:20:00-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:npm (npm run build) on project guide-rest-client-reactjs: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

2023-01-27 10:47 UTC, jakub-pomykala commented on README.adoc
> +The [hotspot=react-library file=1]`React` library imports the `react` package for you to create the [hotspot=ArtistTable file=1]`ArtistTable` function needs to have the `export` declaration as it is
Done

2023-01-27 10:47 UTC, jakub-pomykala commented on README.adoc
> +The [hotspot=useTable file=1]`useTable` hook is used to create a paginated table. The `useTable` hook takes in the [hotspot=table-info file=1]`columns` and [hotspot=Posts file=1]`Posts` objects as pa
Done

2023-01-27 10:49 UTC, jakub-pomykala commented
In regards to [this comment](https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/122#issuecomment-1404305353): I have run end to end and detected no issues.

2023-01-27 21:00 UTC, gkwan-ibm commented
- better make the text in the screenshot bigger
- in the "Try what you’ll build" section, after `liberty:run`, http://localhost:9080 does not show the table 
- should not have following files. It should be created by users
  - `start/src/main/frontend/src/index.js` 
  - `start/src/main/frontend/src/Components/App.js`
  - `start/src/main/frontend/src/Components/ArtistTable.js`
- in the "Importing the HTTP client" subsection, 
  - the `posts` hotspot in "...changes by assigning `response.data` to `posts`." does not highlight any code. 
  - the `convertData` hotspot in "The `convertData` function ...." seems highlight unrelated
- in the "Building and packaging the front end" section, `mvn process-resources` successfully ran at the start directory but the http://localhost:9080 does not show the table

2023-01-30 10:30 UTC, jakub-pomykala commented
Changes done - but once again no issues running the app which straight away displays the table..

2023-01-31 20:26 UTC, gkwan-ibm commented
- better make the text in the screenshot bigger
- in the "Try what you’ll build" section, after `liberty:run`, http://localhost:9080 does not show the table 
- in the "Importing the HTTP client" subsection, 
  - "The `getArtistsInfo()` function ..."  and "...and the `getArtistsInfo()` function."
    -    `getArtistsInfo()`  does not match the code `GetArtistsInfo`
  - "...changes by assigning `response.data` to `posts`." 
    - the `posts` hotspot does not highlight anything 
  - "The `convertData` function ...."
    - although the `convertData` does not highlight anything, it cannot be found in the code. Should remove this statement or need to rewrite something else to explain the code.

2023-02-02 10:08 UTC, jakub-pomykala commented
[Comment](https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/122#issuecomment-1411018416) adressed in [866d616](https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/122/commits/866d616b76347fea8bf94ebc750846d143e2214d) and [78452b4](https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/122/commits/78452b48c1757f80dd6c3503e5ccaa3264c48fd9)

2023-02-02 21:21 UTC, gkwan-ibm commented
- the image has `// tag::tabe[]` and it is even better if can make the width a bit shorter, so that the image can be displayed bigger
- in the "Importing the HTTP client" subsection, 
  -  "The `convertData` function ..." still not make sense.

2023-02-07 09:37 UTC, ReeceNana approved these changes
Ran guide end-to-end. All tests passed, no errors.

2023-02-07 15:27 UTC, gkwan-ibm approved these changes

2023-02-07 16:39 UTC, dmuelle requested changes
ID review, let me know if you have any questions, thanks.

2023-02-07 16:39 UTC, dmuelle commented on README.adoc
> +The [hotspot=react-library file=1]`React` library imports the `react` package for you to create the [hotspot=ArtistTable file=1]`ArtistTable` function needs to have the `export` declaration as it is
```suggestion
The [hotspot=react-library file=1]`React` library imports the `react` package for you to create the [hotspot=ArtistTable file=1]`ArtistTable` function. THis function must have the `export` declaration because it is being exported to the `App.js` module. The [hotspot=posts file=1]`posts` object is initialized using a React Hook that lets you add a state to represent the state of the posts that appear on the paginated table.
```

2023-02-07 16:39 UTC, dmuelle commented on README.adoc
> +The [hotspot=react-library file=1]`React` library imports the `react` package for you to create the [hotspot=ArtistTable file=1]`ArtistTable` function needs to have the `export` declaration as it is
I'm not sure exactly what the first sentence is trying to say- seems like something might be missing. My suggestion is my best guess but please review and adjust as needed.

2023-02-07 16:39 UTC, dmuelle commented on README.adoc
> +The [hotspot=useTable file=1]`useTable` hook is used to create a paginated table. The `useTable` hook takes in the [hotspot=table-info file=1]`columns` and [hotspot=posts file=1]`posts` and `setPosts
```suggestion
The [hotspot=useTable file=1]`useTable` hook creates a paginated table. The `useTable` hook takes in the [hotspot=table-info file=1]`columns`, [hotspot=posts file=1]`posts`, and `setPosts` objects as parameters. It returns a paginated table that is assigned to the [hotspot=table file=1]`table` constant. The [hotspot=table file=1]`table` constant renders the paginated table on the webpage. The [hotspot=return-table file=1]`return` statement returns the paginated table. The [hotspot=useSortBy file=1]`useSortBy` hook sorts the paginated table by the column headers. The [hotspot=usePagination file=1]`usePagination` hook creates the pagination buttons at the bottom of the table that are used to navigate through the paginated table.
```

2023-02-07 16:39 UTC, dmuelle commented on README.adoc
> +The [hotspot=axios]`axios` HTTP call is used to read the artist JSON that contains the data from the sample JSON file in the `resources` directory. When a response is successful, the state of the sys
```suggestion
The [hotspot=axios]`axios` HTTP call is used to read the artist JSON that contains the data from the sample JSON file in the `resources` directory. When a response is successful, the state of the system changes by assigning [hotspot=response-data]`response.data` to [hotspot=posts]`posts`. The [hotspot=for-artists]`artists` and their `albums` JSON data are manipulated to allow them to be accessed by the `ReactTable`. The [hotspot=spread-one]`...rest` or [hotspot=spread-two]`...album` object spread syntax is designed for simplicity. To learn more about it, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals[Spread in object literals^].
```

I've removed "relatively new" here only because that description is likely to go out of date over time.

2023-02-07 18:16 UTC, dmuelle approved these changes
LGTM, thanks

2023-02-07 18:44 UTC, merged