Update react nextjs
OpenLiberty/draft-guide-rest-client-reactjs pull request #199
Opened 2024-07-02 21:43 UTC by Ruilin-Ma

2024-08-09 16:25 UTC, gkwan-ibm commented
- [ ] in pom.xml, under the `maven-resources-plugin`, format the content in between the  `<executions>` and `</executions>` tags better 
- **Creating the default page**
  - [ ] "The `page.jsx` file will be act ..."  -> "The `page.jsx` file will be acted ..."  or "The `page.jsx` file will act ..." 
  - [ ] "...documentation on [Pages and Layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts)", is it better to link Pages and Layouts to different docs?
- **Building and packaging the front-end**
  - [ ] after run `mvn process-resources`, the `http://localhost:9080/` does not work. After press `r` in dev mode console to restart the app, the link work
- not sure which terms are correct: `front end`/`front-end`/`frontend` and  `back end`/`back-end`/`backend`
  - [ ] need ID to confirm and update the guide to use them consistently

2024-08-14 20:31 UTC, gkwan-ibm commented on README.adoc
> +For more detailed information on structuring `Pages` and `Layouts` in `Next.js`, please refer to the `Next.js` documentation on https://nextjs.org/docs/app/building-your-application/routing/pages[Pag
missed a period at the end of the statement

2024-08-14 20:34 UTC, gkwan-ibm commented on README.adoc
> +== Creating ArtistTable React component
no need to change the section title

2024-08-14 20:44 UTC, gkwan-ibm commented on README.adoc
> +`Next.js` supports a variety of testing tools. This guide uses `Vitest` for unit testing the React components, with the test file [hotspot file]`App.test.jsx` located in `src/main/frontend/__tests__/
miss a period at the end

2024-08-14 21:16 UTC, gkwan-ibm commented on README.adoc
> +The React application in this guide is provided and configured for you in the `src/main/frontend` directory. The application uses https://nextjs.org/[Next.js], one of the https://react.dev/learn/star
- miss the `^` char in the links
  - `[Next.js]` -> `[Next.js^]`
  - `[React-powered frameworks]` -> `[React-powered frameworks^]`

2024-08-14 21:26 UTC, gkwan-ibm commented
- for `sed -i 's=http://localhost:9080/artists='"https://${USERNAME}-9080.$(echo $TOOL_DOMAIN | sed 's/\.labs\./.proxy./g')/artists"'=' src/main/webapp/static/js/main.2d7e902e.js` 
  - update `main.2d7e902e.js` to `main.1bcb490d.js`

2024-08-19 15:01 UTC, shin19991207 approved these changes
Tested on Skills Network and Windows, no issues.

2024-08-19 18:44 UTC, dmuelle requested changes
ID review- left a some suggestions per IBM style.

GLobally- only hyphenate front end/ back end when they are used as adjectives ie

Build a front-end component
but
Build the front end of your application

Also, web page is 2 words. 

lmk if you have any questions-  thanks!

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The React application in this guide is provided and configured for you in the `src/main/frontend` directory. The application uses https://nextjs.org/[Next.js^], one of the https://react.dev/learn/sta
```suggestion
The React application in this guide is provided and configured for you in the `src/main/frontend` directory. The application uses https://nextjs.org/[Next.js^], a https://react.dev/learn/start-a-new-react-project[React-powered frameworks^], to set up the modern React application. The `Next.js` framework provides a powerful environment for learning and building React applications, with features like server-side rendering, static site generation, and easy API routes. It is the best way to start building a highly performant React application.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The REST service that provides the resources was written for you in advance in the back-end of the application, and it responds with the [hotspot]`artists.json` in the `src/resources` directory. You
```suggestion
The REST service that provides the resources was written for you in advance in the back end of the application, and it responds with the [hotspot]`artists.json` file  in the `src/resources` directory. You will implement a ReactJS client as the front end of your application, which consumes this JSON file and displays its contents on a single web page. 
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The `finish` directory in the root of this guide contains the finished application. The React front-end is already pre-built for you and the static files from the production build can be found in the
```suggestion
The `finish` directory in the root of this guide contains the finished application. The React front end is already pre-built for you and the static files from the production build can be found in the `src/main/webapp/_next/static` directory.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +All the dependencies for the React front-end are listed in `src/main/frontend/src/package.json` and are installed before the build process by the `frontend-maven-plugin`. Additionally, `CSS` styleshe
```suggestion
All the dependencies for the React front end are listed in the  `src/main/frontend/src/package.json` file and are installed before the build process by the `frontend-maven-plugin`. Also, `CSS` stylesheets files are available in the `src/main/frontend/src/styles` directory.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The front-end of your application uses Node.js to build your React code. The Maven project is configured for you to install Node.js and produce the production files, which are copied to the web conte
```suggestion
The front end of your application uses Node.js to build your React code. The Maven project is configured for you to install Node.js and produce the production files, which are copied to the web content of your application.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +You'll need to create the entry point of your React application. In the latest version of `Next.js`, it's recommended to use the https://nextjs.org/docs/app/building-your-application/routing/defining
```suggestion
Create the entry point of your React application. The latest version of `Next.js` recommends  you use the https://nextjs.org/docs/app/building-your-application/routing/defining-routes[App Router], which centralizes routing logic under the `app` directory. 
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The `page.jsx` file will serve as a container for all other components. When React component [hotspot=createHome file=0]`Home` is rendered, the [hotspot=displayArtistTable file=0]`ArtistTable` compon
```suggestion
The `page.jsx` file is a container for all other components. When the [hotspot=createHome file=0]`Home` React component  is rendered, the [hotspot=displayArtistTable file=0]`ArtistTable` components content are displayed.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +In order to render the pages correctly, it is required to add a [hotspot file=1]`layout.jsx` file which defines the `RootLayout` containing the UI that shared across all routes.
```suggestion
To render the pages correctly, add a [hotspot file=1]`layout.jsx` file that defines the `RootLayout` containing the UI that are shared across all routes.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +For more detailed information on structuring `Pages` and `Layouts` in `Next.js`, please refer to the `Next.js` documentation on https://nextjs.org/docs/app/building-your-application/routing/pages[Pag
```suggestion
For more detailed information, see the `Next.js` documentation on https://nextjs.org/docs/app/building-your-application/routing/pages[Pages^] and https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates[Layouts^].
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +A React web application is a collection of components, and each component has a specific function. You will create a component that are used in the application to acquire and display data from the RE
```suggestion
A React web application is a collection of components, and each component has a specific function. You will create a component that the application uses to acquire and display data from the REST API. 
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +At the top of the file, the [hotspot=render-client file=0]`use client` directive is used to indicate the `ArtistTable` component will be rendered on the client side.
```suggestion
At the beginning of the file, the [hotspot=render-client file=0]`use client` directive indicates the `ArtistTable` component is rendered on the client side.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +To display the returned data, you will use pagination. Pagination is the process of separating content into discrete pages, and it can be used for handling data sets in React. In your application, yo
```suggestion
To display the returned data, you will use pagination. Pagination is the process of separating content into discrete pages, and you can use it for handling data sets in React. In your application, you'll render the columns in the paginated table. The [hotspot=table-info file=0]`columns` constant defines the table that is present on the web page.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The [hotspot=useReactTable file=0]`useReactTable` hook creates a table instance. The hook takes in the [hotspot=table-info file=0]`columns`, [hotspot=posts file=0]`posts` as parameters. The [hotspot=
```suggestion
The [hotspot=useReactTable file=0]`useReactTable` hook creates a table instance. The hook takes in the [hotspot=table-info file=0]`columns` and  [hotspot=posts file=0]`posts` as parameters. The [hotspot=getCoreRowModel file=0]`getCoreRowModel` function is included for the generation of the core row model of the table, which serves as the foundational row model upon pagination and sorting build. The [hotspot=getPaginationRowModel file=0]`getPaginationRowModel` function applies pagination to the core row model, returning a row model that includes only the rows that should be displayed on the current page based on the pagination state. In addition, the [hotspot=getSortedRowModel file=0]`getSortedRowModel` function sorts the paginated table by the column headers then applies the changes to the row model. The paginated table instance is assigned to the [hotspot=table file=0]`table` constant, which renders the paginated table on the web page.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The [hotspot=get-posts]`GetArtistsInfo()` function uses the Axios API to fetch data from your back-end. This function is called when the `ArtistTable` is rendered to the page using the [hotspot=useEf
```suggestion
The [hotspot=get-posts]`GetArtistsInfo()` function uses the Axios API to fetch data from your back end. This function is called when the `ArtistTable` is rendered to the page using the [hotspot=useEffect]`useEffect()` React lifecycle method.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +After you successfully build your components, you need to build the front-end and package your application. The Maven `process-resources` goal generates the Node.js resources, creates the front-end p
```suggestion
After you successfully build your components, you need to build the front end and package your application. The Maven `process-resources` goal generates the Node.js resources, creates the front-end production build, and copies and processes the resources into the destination directory. 
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +In a new command-line session, build the front-end by running the following command in the `start` directory:
```suggestion
In a new command-line session, build the front end by running the following command in the `start` directory:
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +The build may take a few minutes to complete. You can rebuild the front-end at any time with the Maven `process-resources` goal. Any local changes to your JavaScript and HTML are picked up when you b
```suggestion
The build may take a few minutes to complete. You can rebuild the front end at any time with the Maven `process-resources` goal. Any local changes to your JavaScript and HTML are picked up when you build the front-end.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +Navigate to the http://localhost:9080[http://localhost:9080^] web application root to view the front-end of your application.
```suggestion
Navigate to the http://localhost:9080[http://localhost:9080^] web application root to view the front end of your application.
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +Click the following button to view the front-end of your application:
```suggestion
Click the following button to view the front end of your application:
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +`Next.js` supports a variety of testing tools. This guide uses `Vitest` for unit testing the React components, with the test file [hotspot file]`App.test.jsx` located in `src/main/frontend/__tests__/
```suggestion
`Next.js` supports various testing tools. This guide uses `Vitest` for unit testing the React components, with the test file [hotspot file]`App.test.jsx` located in `src/main/frontend/__tests__/` directory. The `App.test.jsx` file is a simple JavaScript file that tests against the `page.jsx` component. No explicit test cases are written for this application. To learn more about `Vitest`, see https://nextjs.org/docs/app/building-your-application/testing/vitest[Setting up Vitest with Next.js].
```

2024-08-19 18:44 UTC, dmuelle commented on README.adoc
> +To run the default test, you can add the [hotspot=node-tests file=1]`testing` configuration to the `frontend-maven-plugin`. Rerun the Maven `process-resources` goal to rebuild the front-end and run t
```suggestion
To run the default test, you can add the [hotspot=node-tests file=1]`testing` configuration to the `frontend-maven-plugin`. Rerun the Maven `process-resources` goal to rebuild the front end and run the tests.
```

2024-08-20 13:12 UTC, dmuelle commented on README.adoc
> +The React application in this guide is provided and configured for you in the `src/main/frontend` directory. The application uses https://nextjs.org/[Next.js^], a https://react.dev/learn/start-a-new-
```suggestion
The React application in this guide is provided and configured for you in the `src/main/frontend` directory. The application uses https://nextjs.org/[Next.js^], a https://react.dev/learn/start-a-new-react-project[React-powered framework^], to set up the modern React application. The `Next.js` framework provides a powerful environment for learning and building React applications, with features like server-side rendering, static site generation, and easy API routes. It is the best way to start building a highly performant React application.
```

2024-08-20 15:49 UTC, Ruilin-Ma commented
Hi @dmuelle, thanks for your review and suggestions. Appreciate that!

2024-08-20 16:06 UTC, dmuelle approved these changes
LGTM, thanks @Ruilin-Ma

2024-08-20 20:47 UTC, gkwan-ibm approved these changes

2024-08-20 22:04 UTC, merged